name: CICD-prod

on:
  push:
    branches: [ "test" ]

jobs:
  build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Login to Hub
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        
        - name: Run make build
          env: 
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            GITHUB_SHA: ${{ github.sha }}
          run: make build

        - name: Run make build test
          env: 
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            GITHUB_SHA: ${{ github.sha }}
          run: make build-test

        - name: Run make push test
          env: 
              DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
              DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          run: make push-test
          
        - name: Notify infra repo to deploy
          run: |
            IMAGE_REPO="${{ secrets.DOCKERHUB_USERNAME }}/notes-frontend"
            IMAGE_TAG="${{ github.sha }}"
            curl -X POST \
              -H "Authorization: token ${{ secrets.PAT_CICD }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/Jonny-JD/NotestServer-Test-/dispatches \
              -d '{"event_type": "deploy-frontend-tests", "client_payload": {"repository": "'"$IMAGE_REPO"'", "tag": "'"$IMAGE_TAG"-test"'"}}'
