name: CICD-test

on:
  push:
    branches: [ "test" ]

jobs:
  build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          
        - name: Notify tests repo to deploy
          run: |
            IMAGE_REPO="${{ secrets.DOCKERHUB_USERNAME }}/notes-frontend"
            IMAGE_TAG="${{ github.sha }}-test"
            curl -X POST \
              -H "Authorization: token ${{ secrets.PAT_CICD }}" \
              -H "Accept: application/vnd.github+json" \
              -H "Content-Type: application/json" \
              https://api.github.com/repos/Jonny-JD/NotestServer-Test-/dispatches \
              -d "{\"event_type\": \"deploy-frontend-tests\", \"client_payload\": {\"repository\": \"$IMAGE_REPO\", \"tag\": \"$IMAGE_TAG\"}}"
